# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stuff.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import mysql.connector
from PyQt5 import QtCore, QtGui, QtWidgets

def connect_database():
    try:
        #creating and connecting database
        mydb = mysql.connector.connect(
            host = "localhost",
            user = "root",
            passwd = "QsxfThm,1",
            database = "student_database"
        )
        return mydb
    except mysql.connector.Error as err:
        print(f"Error: {err}")
        return None

        mycursor = mydb.cursor()

        mycursor.execute("show tables")

        for tb in mycursor:
            print(tb)



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        connect_database()





        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1170, 925)
        MainWindow.setStyleSheet("background-color: rgb(98, 160, 234);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 20, 1081, 141))
        self.groupBox.setObjectName("groupBox")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 30, 80, 30))
        self.plainTextEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(300, 60, 200, 30))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(300, 30, 91, 30))
        self.plainTextEdit_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(550, 60, 200, 30))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(550, 30, 111, 30))
        self.plainTextEdit_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setGeometry(QtCore.QRect(800, 60, 200, 30))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(800, 30, 111, 30))
        self.plainTextEdit_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(30, 60, 191, 27))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(90, 190, 181, 151))
        self.groupBox_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setGeometry(QtCore.QRect(40, 50, 109, 25))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setGeometry(QtCore.QRect(40, 80, 109, 25))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(40, 110, 109, 25))
        self.radioButton_3.setObjectName("radioButton_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(410, 200, 191, 80))
        self.groupBox_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.groupBox_3.setObjectName("groupBox_3")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox.setGeometry(QtCore.QRect(0, 20, 191, 27))
        self.comboBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(710, 200, 311, 201))
        self.groupBox_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.groupBox_4.setObjectName("groupBox_4")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox.setGeometry(QtCore.QRect(30, 40, 161, 25))
        self.checkBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_2.setGeometry(QtCore.QRect(30, 70, 281, 25))
        self.checkBox_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_3.setGeometry(QtCore.QRect(30, 160, 151, 25))
        self.checkBox_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_4.setGeometry(QtCore.QRect(30, 130, 251, 25))
        self.checkBox_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_5.setGeometry(QtCore.QRect(30, 100, 121, 25))
        self.checkBox_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_5.setObjectName("checkBox_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(120, 460, 861, 161))
        self.groupBox_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton.setGeometry(QtCore.QRect(20, 50, 87, 27))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 50, 87, 27))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 50, 87, 27))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_4.setGeometry(QtCore.QRect(390, 50, 87, 27))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_5.setGeometry(QtCore.QRect(510, 50, 87, 27))
        self.pushButton_5.setStyleSheet("color: rgb(165, 29, 45);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_6.setGeometry(QtCore.QRect(620, 50, 101, 27))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_7.setGeometry(QtCore.QRect(740, 50, 87, 27))
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_6.setGeometry(QtCore.QRect(380, 100, 113, 27))
        self.lineEdit_6.setObjectName("lineEdit_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1170, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Students Bio Data"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "Title"))
        self.plainTextEdit_2.setPlainText(_translate("MainWindow", "First Name"))
        self.plainTextEdit_3.setPlainText(_translate("MainWindow", "Second Name"))
        self.plainTextEdit_4.setPlainText(_translate("MainWindow", "Surname"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "SELECT *"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "MR"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "MRS"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "DR"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "PROFF"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "SIR"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Select your Gender"))
        self.radioButton.setText(_translate("MainWindow", "Male"))
        self.radioButton_2.setText(_translate("MainWindow", "Female"))
        self.radioButton_3.setText(_translate("MainWindow", "Other"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Load your School"))
        self.comboBox.setItemText(0, _translate("MainWindow", "SELECT SCHOOL *"))
        self.comboBox.setItemText(1, _translate("MainWindow", "EDUCATION"))
        self.comboBox.setItemText(2, _translate("MainWindow", "SIST"))
        self.comboBox.setItemText(3, _translate("MainWindow", "SETHURED"))
        self.comboBox.setItemText(4, _translate("MainWindow", "MEDICINE"))
        self.comboBox.setItemText(5, _translate("MainWindow", "LAW"))
        self.comboBox.setItemText(6, _translate("MainWindow", "SASS"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Choose Semester Units"))
        self.checkBox.setText(_translate("MainWindow", "Python Programming"))
        self.checkBox_2.setText(_translate("MainWindow", "Object Oriented Programming in Java"))
        self.checkBox_3.setText(_translate("MainWindow", "Wireless Networks"))
        self.checkBox_4.setText(_translate("MainWindow", "Introduction to web Programming"))
        self.checkBox_5.setText(_translate("MainWindow", "Cyber Security"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Select The Action"))
        self.pushButton.setText(_translate("MainWindow", "Add New"))
        self.pushButton_2.setText(_translate("MainWindow", "Save"))
        self.pushButton_3.setText(_translate("MainWindow", "Modify"))
        self.pushButton_4.setText(_translate("MainWindow", "Read"))
        self.pushButton_5.setText(_translate("MainWindow", "Delete"))
        self.pushButton_6.setText(_translate("MainWindow", "Move Previous"))
        self.pushButton_7.setText(_translate("MainWindow", "Move Next"))
        self.lineEdit_6.setText(_translate("MainWindow", "Search"))
        root.mainloop()







    